#tomcat配置
server:
      tomcat:
            max-connections: 200 #最大连接数
            accept-count: 800  #最大等待数

      port: 10010   #设置端口号
---  # 可以用来分割 标识下面都是同一个文档


#mysql
spring:
      datasource:
            url: "jdbc:mysql://127.0.0.1:3306/singing?characterEncoding=utf8&autoReconnect=true&autoReconnectForPools=true&connectTimeout=0&useSSL=false&allowMultiQueries=true"
            username: "SingingClubVotingProject"
            password: "SingingClubVotingProject"
            driver-class-name: "com.mysql.jdbc.Driver"


            #druid数据库连接池
            type: com.alibaba.druid.pool.DruidDataSource
mybatis:
      mapper-locations: classpath:/mybatis/*.xml
      type-aliases-package: com.example.singingclubvotingproject.idao
---
#
##reids
#spring.data.redis:
#      host: 127.0.0.1
#      port: 6379
#      password: 123456
#---



